version: '3.9'

services:
  app:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "35432:5432"

  redis:
    container_name: redis
    image: redis

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis

volumes:
  postgres_data: