version: '3.9'

services:
  app:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./app/:/code/app
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "35432:5432"

volumes:
  postgres_data: